"""add_notification_and_preference_fields

Revision ID: a18a2d55b0da
Revises: 2877e0a0ada6
Create Date: 2026-08-19 16:56:06.888338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a18a2d55b0da'
down_revision: Union[str, Sequence[str], None] = '2877e0a0ada6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_logs', sa.Column('farmer_id', sa.String(length=36), nullable=True))
    op.add_column('notification_logs', sa.Column('field_id', sa.String(length=36), nullable=True))
    op.add_column('notification_logs', sa.Column('severity', sa.String(length=50), nullable=True))
    op.add_column('notification_logs', sa.Column('recommended_action', sa.String(length=500), nullable=True))
    op.add_column('notification_logs', sa.Column('notification_type', sa.String(length=100), nullable=True))
    op.add_column('notification_logs', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.add_column('notification_logs', sa.Column('notification_metadata', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'notification_logs', 'fields', ['field_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notification_logs', 'users', ['farmer_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('quiet_hours_start', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('quiet_hours_end', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('critical_alerts_only', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'critical_alerts_only')
    op.drop_column('users', 'quiet_hours_end')
    op.drop_column('users', 'quiet_hours_start')
    op.drop_constraint(None, 'notification_logs', type_='foreignkey')
    op.drop_constraint(None, 'notification_logs', type_='foreignkey')
    op.drop_column('notification_logs', 'notification_metadata')
    op.drop_column('notification_logs', 'read_at')
    op.drop_column('notification_logs', 'notification_type')
    op.drop_column('notification_logs', 'recommended_action')
    op.drop_column('notification_logs', 'severity')
    op.drop_column('notification_logs', 'field_id')
    op.drop_column('notification_logs', 'farmer_id')
    # ### end Alembic commands ###
