"""Generate the repository-derived QA workbook. No application code is modified."""
from pathlib import Path
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.formatting.rule import CellIsRule
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.utils import get_column_letter

OUT = Path(__file__).with_name("AI_Irrigation_System_Test_Cases.xlsx")
HEADERS = [
    "Test Case ID", "Module", "Sub Module", "Test Case Description",
    "Preconditions / Dependencies", "TC Ready for Testing", "Functional", "SIT",
    "Performance", "Test Steps", "Expected Result", "Actual Result", "Status",
    "Priority", "Test Data", "Defect ID", "Remarks",
]

def tc(module, sub, description, dependencies, steps, expected, priority="HIGH", data="<TEST_DATA>",
       status="NOT TESTED", actual="Not Executed", ready="YES", functional="X", sit="", perf="", defect="", remarks=""):
    return [module, sub, description, dependencies, ready, functional, sit, perf, steps, expected,
            actual, status, priority, data, defect, remarks]

CASES = [
tc("Quality Checks", "Frontend lint", "Run the repository ESLint script.", "Node modules installed.", "1. Run npm run lint in frontend.", "ESLint exits with code 0.", "MEDIUM", "N/A", "PASS", "npm run lint completed with exit code 0.", remarks="Executed 2026-08-30; frontend/package.json."),
tc("Quality Checks", "TypeScript", "Run TypeScript type checking without emission.", "Node modules installed.", "1. Run npx tsc --noEmit in frontend.", "TypeScript exits with code 0.", "MEDIUM", "N/A", "PASS", "npx tsc --noEmit completed with exit code 0.", remarks="Executed 2026-08-30; no package typecheck script exists."),
tc("Quality Checks", "Backend tests", "Execute the existing pytest suite.", "pytest and configured PostgreSQL/database must be available.", "1. Run pytest -q at repository root.", "Tests execute and report actual outcomes.", "HIGH", "N/A", "BLOCKED", "Not Executed — pytest command is not installed in this environment.", "BLOCKED", remarks="Existing tests import FastAPI TestClient and SessionLocal; requirements.txt does not declare pytest."),
tc("Quality Checks", "Production build", "Create an optimized Next.js production build.", "Node modules and process-spawn permission.", "1. Run npm run build in frontend.", "Build completes successfully.", "HIGH", "N/A", "BLOCKED", "Build reached Next.js compilation then failed: spawn EPERM.", "BLOCKED", remarks="Environment execution constraint observed 2026-08-30; investigate locally/CI."),
tc("Authentication", "Farmer registration", "Register a FARMER account through POST /users/register.", "API and PostgreSQL available.", "1. Submit valid Farmer payload. 2. Inspect response and stored user.", "200 token response; role FARMER, status ACTIVE, active account.", data="<VALID_FARMER_ACCOUNT>", sit="X", remarks="backend/api/routes.py: /users/register."),
tc("Authentication", "Admin registration", "Register an ADMIN account through POST /users/register.", "API and PostgreSQL available.", "1. Submit valid Admin payload. 2. Inspect response and stored user.", "200 pending response; role ADMIN_PENDING, status PENDING, inactive account.", data="<VALID_ADMIN_ACCOUNT>", sit="X", remarks="backend/api/routes.py: /users/register."),
tc("Authentication", "Duplicate registration", "Submit an email that already exists.", "Existing user account.", "1. Register using existing email.", "HTTP 400 Email already registered.", data="<EXISTING_EMAIL>", remarks="Actual status code implemented: 400."),
tc("Authentication", "Invalid registration role", "Attempt registration with SUPER_ADMIN or another unsupported role.", "API available.", "1. Submit registration with invalid role.", "HTTP 400; registration is rejected.", data="<INVALID_ROLE>", remarks="SUPER_ADMIN is not accepted by role allow-list."),
tc("Authentication", "Login", "Log in with a valid active account.", "Existing active account.", "1. POST valid email and password to /users/login.", "HTTP 200 bearer access token returned.", data="<VALID_FARMER_ACCOUNT>", sit="X"),
tc("Authentication", "Invalid credentials", "Log in using bad credentials.", "API available.", "1. POST invalid password to /users/login.", "HTTP 400 Incorrect email or password.", data="<INVALID_CREDENTIALS>"),
tc("Authentication", "Inactive status", "Log in as PENDING, REJECTED, or SUSPENDED user.", "Accounts in each status.", "1. POST valid credentials for each account.", "HTTP 403 with status-specific denial.", data="<PENDING_ADMIN_ACCOUNT>"),
tc("Authentication", "JWT protected route", "Call an authenticated route with missing, malformed, and expired bearer tokens.", "API available; expired token fixture.", "1. GET /users/profile without token. 2. Repeat malformed and expired.", "HTTP 401 for invalid authentication.", data="<INVALID_OR_EXPIRED_JWT>", sit="X", remarks="JWT decoding is enforced by get_current_user."),
tc("Authentication", "Logout", "Verify a server-side logout/session invalidation endpoint.", "API available.", "1. Inspect routes. 2. Attempt documented logout flow if present.", "A logout endpoint revokes/ends server-side session if implemented.", data="N/A", status="NOT IMPLEMENTED", actual="No logout endpoint is defined in backend/api/routes.py; frontend removes local token on 401 only.", ready="NO", remarks="No test result fabricated."),
tc("RBAC", "Farmer admin denial", "Use a FARMER token on admin statistics and pending-request routes.", "Farmer account and API/database.", "1. GET /admin/stats. 2. GET /admin/requests.", "HTTP 403 on restricted admin access.", data="<VALID_FARMER_ACCOUNT>", sit="X"),
tc("RBAC", "Admin approval", "SUPER_ADMIN approves a PENDING admin registration.", "Pending admin and Super Admin account.", "1. POST /admin/requests/{id}/approve. 2. Login as approved admin.", "User becomes ADMIN/ACTIVE; login becomes available.", data="<PENDING_ADMIN_ACCOUNT>", sit="X", remarks="Requires super-admin credentials; never place password in workbook."),
tc("RBAC", "Admin rejection", "SUPER_ADMIN rejects a PENDING admin registration.", "Pending admin and Super Admin account.", "1. POST /admin/requests/{id}/reject. 2. Attempt login.", "User is REJECTED; login remains blocked.", data="<PENDING_ADMIN_ACCOUNT>", sit="X"),
tc("RBAC", "Super Admin protection", "Verify the protected account cannot be modified or deleted.", "Super Admin and another privileged account.", "1. Attempt status update/delete for sunkaraajay66@gmail.com. 2. Attempt self-promotion as another user.", "Operations are denied according to endpoint protections.", data="<SUPER_ADMIN_ACCOUNT>", sit="X", remarks="Seed/test code identifies the sole intended account; no password recorded."),
tc("Farm Management", "Create/list/delete", "Create, list, and delete a farm owned by the signed-in user.", "Farmer account and API/database.", "1. POST /farms. 2. GET /farms. 3. DELETE returned id.", "Owned farm is returned and deletion succeeds.", data="<TEST_FARM>", sit="X"),
tc("Farm Management", "Ownership isolation", "Attempt to delete Farmer A farm using Farmer B token.", "Two farmers and Farmer A farm.", "1. DELETE /farms/{farmer-a-id} using Farmer B token.", "HTTP 404 access denied.", data="<FARMER_A_FARM_ID>", sit="X"),
tc("Farm Management", "Update", "Verify an owned farm update endpoint.", "API available.", "1. Inspect routes. 2. Attempt PUT/PATCH if exposed.", "Farm update endpoint supports validated owned update.", data="<TEST_FARM>", status="NOT IMPLEMENTED", actual="No PUT/PATCH /farms/{id} route is defined.", ready="NO"),
tc("Field & Crop", "Create/list/delete field", "Manage fields for an owned farm.", "Farmer owns farm.", "1. POST /fields. 2. GET /fields?farm_id=. 3. DELETE /fields/{id}.", "Only fields under the owned farm are managed.", data="<TEST_FIELD>", sit="X"),
tc("Field & Crop", "Field ownership", "Access another farmer's field through field routes.", "Two farmers and a field.", "1. GET/DELETE using non-owner token.", "HTTP 404 access denied.", data="<OTHER_FARMER_FIELD_ID>", sit="X"),
tc("Field & Crop", "Field update", "Verify an owned field update endpoint.", "API available.", "1. Inspect routes. 2. Attempt PUT/PATCH if exposed.", "Field update endpoint supports validated owned update.", data="<TEST_FIELD>", status="NOT IMPLEMENTED", actual="No PUT/PATCH /fields/{id} route is defined.", ready="NO"),
tc("Field & Crop", "Crop lifecycle", "Create, update, and list crops for an owned field.", "Owned field.", "1. POST /crops. 2. PUT /crops/{id}. 3. GET /crops?field_id=.", "Owned crop is created/updated/listed; invalid ownership is rejected.", data="<TEST_CROP>", sit="X"),
tc("Sensors & Telemetry", "Sensor registration", "Register and list a sensor against an owned field.", "Owned field.", "1. POST /sensors. 2. GET /sensors?field_id=.", "Sensor is linked to owned field.", data="<TEST_SENSOR>", sit="X"),
tc("Sensors & Telemetry", "Telemetry and recommendation", "Post valid telemetry for an owned crop/sensor.", "Owned crop and sensor; ML artifacts.", "1. POST /sensors/{sensor_id}/telemetry. 2. Inspect recommendation.", "Telemetry is recorded and a recommendation response is produced.", data="<VALID_TELEMETRY>", sit="X", remarks="POST route invokes ML and background work."),
tc("Sensors & Telemetry", "Telemetry invalid values", "Submit invalid/missing telemetry values and invalid ownership mappings.", "API available.", "1. Submit malformed payload. 2. Use foreign crop/sensor ids.", "Pydantic validation or ownership denial; no unauthorized record.", data="<INVALID_TELEMETRY>", sit="X"),
tc("Weather", "Weather summary", "Request weather for an owned farm or valid coordinates.", "Weather provider configuration/network.", "1. GET /weather. 2. Verify current/hourly/daily response.", "Configured provider response is normalized without crash.", data="<OWNED_FARM_ID>", sit="X", remarks="backend/services/weather.py uses Open-Meteo/fallback naming, not a direct OpenWeather-only implementation."),
tc("Weather", "Provider failure", "Simulate weather timeout/provider error during alert evaluation.", "Controllable weather mock/test environment.", "1. Make provider fail. 2. POST /alerts/evaluate.", "Alert evaluation handles exception and continues using defaults/fallback behavior.", data="<WEATHER_FAILURE_FIXTURE>", sit="X", remarks="alerts.py catches weather exceptions."),
tc("Irrigation", "Recommendation status", "Update an owned recommendation to supported lifecycle statuses.", "Owned recommendation.", "1. PUT /recommendations/{id} with applied volume and each supported status.", "Owned recommendation persists accepted status and volume.", data="<TEST_RECOMMENDATION>", sit="X", remarks="Implemented values include pending/applied/skipped/deferred/scheduled/started/completed/failed/cancelled."),
tc("Irrigation", "History and water usage", "Retrieve farmer schedule, history, and weekly water usage.", "Farmer data exists.", "1. GET /farmer/schedule. 2. GET history and water usage.", "Only owned data is returned with expected aggregation.", data="<VALID_FARMER_ACCOUNT>", sit="X"),
tc("Alert Engine", "Critical low moisture", "Evaluate moisture below critical threshold with low rain probability.", "Field, crop, telemetry, threshold configuration.", "1. Set moisture below critical. 2. Set forecast rain below configured threshold. 3. Evaluate.", "Active CRITICAL irrigation_required alert; duration constrained 15–60 min.", data="<CRITICAL_MOISTURE_FIXTURE>", sit="X", remarks="Rule in backend/services/alerts.py; defaults critical 25, warning 35, rain 0.60."),
tc("Alert Engine", "Warning low moisture", "Evaluate moisture from critical inclusive to warning exclusive with low rain chance.", "Field/crop/telemetry.", "1. Set moisture in warning band. 2. Evaluate.", "WARNING irrigation_required alert.", data="<WARNING_MOISTURE_FIXTURE>", sit="X"),
tc("Alert Engine", "Rain-aware deferral", "Evaluate low/critical moisture with rain probability at/above configured threshold.", "Forecast fixture.", "1. Set low moisture. 2. Set rain probability at threshold. 3. Evaluate.", "rain_expected alert; INFO for warning band, WARNING for critical band.", data="<RAIN_THRESHOLD_FIXTURE>", sit="X"),
tc("Alert Engine", "Overwatering", "Evaluate moisture greater than configured overwatering threshold.", "Telemetry and thresholds.", "1. Set moisture > overwatering threshold. 2. Evaluate.", "WARNING overwatering_risk alert.", data="<OVERWATERING_FIXTURE>", sit="X"),
tc("Alert Engine", "Sensor freshness", "Evaluate active sensor with 31–60 minute-old telemetry, >60 minute telemetry, and no telemetry.", "Active sensor and controlled timestamps.", "1. Evaluate each age scenario.", "WARNING missing telemetry after warning timeout; CRITICAL failure after critical timeout/no telemetry.", data="<SENSOR_TIMESTAMP_FIXTURE>", sit="X", remarks="Timeout defaults are settings-driven (30/60 minutes)."),
tc("Alert Engine", "No sensors", "Evaluate a field with no registered sensor.", "Field with no sensors.", "1. POST /alerts/evaluate.", "CRITICAL sensor_data_missing alert.", data="<FIELD_WITHOUT_SENSOR>", sit="X"),
tc("Alert Engine", "Predictive depletion", "Evaluate the derived 6/12/24-hour moisture prediction against critical threshold.", "Field/crop/current telemetry/weather fixture.", "1. Set inputs to cross threshold at each horizon. 2. Evaluate.", "predicted_low_moisture: CRITICAL at 6/12h; WARNING at 24h.", data="<PREDICTIVE_ALERT_FIXTURE>", sit="X", remarks="Current implementation is formula-based depletion in alerts.py, not LSTM inference."),
tc("Alert Engine", "Irrigation outcomes", "Evaluate recommendation statuses COMPLETED and FAILED.", "Owned crop and recommendation.", "1. Set latest status. 2. Evaluate twice.", "INFO completion or CRITICAL failure alert; same recommendation is not re-alerted.", data="<RECOMMENDATION_STATUS_FIXTURE>", sit="X"),
tc("Alert Engine", "Deduplication and resolution", "Evaluate identical active condition twice, normalize it, then re-trigger.", "Repeatable field fixture.", "1. Evaluate trigger twice. 2. Normalize and evaluate. 3. Trigger again.", "No duplicate active type; existing alert resolves; later condition can create new alert.", data="<ALERT_LIFECYCLE_FIXTURE>", sit="X", remarks="Deduplication is active-alert-type based; no explicit cooldown found."),
tc("Notifications", "In-app delivery", "Dispatch an alert notification and retrieve it for its farmer.", "Alert, farmer-owned field/farm, database.", "1. Dispatch alert. 2. GET /farmer/notifications. 3. Verify metadata.", "Persisted in-app notification appears for the owner.", data="<TEST_ALERT>", sit="X"),
tc("Notifications", "Unread/read lifecycle", "Verify unread count, single read, and mark-all read.", "Unread notifications.", "1. GET unread count. 2. PATCH one read. 3. PATCH/POST read-all.", "Counts and read flags update only within owned farms.", data="<TEST_NOTIFICATION>", sit="X"),
tc("Notifications", "Preferences", "Get/init and update notification preferences.", "Authenticated farmer and database.", "1. GET preferences. 2. PUT valid push/SMS/quiet-hours/language settings.", "Preferences and user fields persist.", data="<VALID_NOTIFICATION_PREFERENCES>", sit="X"),
tc("Web Push", "Subscription", "Register/update an authenticated browser push subscription.", "VAPID public key and browser subscription fixture.", "1. GET public key. 2. POST subscription twice.", "Subscription persists and duplicate endpoint updates rather than duplicates.", data="<PUSH_SUBSCRIPTION>", sit="X"),
tc("Web Push", "Delivery/click", "Verify push permission, delivery, service-worker handling, and deep link.", "HTTPS browser, VAPID/private key, push-capable environment.", "1. Grant/deny permission. 2. Send push. 3. Click notification.", "Delivery behavior and target URL are verified in a real browser.", data="<WEB_PUSH_FIXTURE>", status="NOT TESTED", remarks="sw.js handles push and notificationclick; browser delivery was not executed."),
tc("PWA & Offline", "Manifest", "Validate manifest metadata and all declared icon assets.", "Built/running frontend or static asset inspection.", "1. Fetch manifest. 2. Verify icon files and declared sizes/purpose.", "Manifest has valid standalone start_url, theme/background, normal and maskable 192/512 icons.", data="N/A", remarks="Static implementation found; installability not executed."),
tc("PWA & Offline", "Service worker cache", "Verify install, cache invalidation and static navigation fallback offline.", "Browser DevTools/service worker test environment.", "1. Install SW. 2. Load online. 3. Go offline. 4. Navigate cached/static routes.", "Actual cached behavior matches stale-while-revalidate code and missing API behavior is clearly identified.", data="<OFFLINE_BROWSER>", sit="X", remarks="sw.js caches root/manifest/favicon initially; API/farmer routes bypass cache."),
tc("PWA & Offline", "Offline data behavior", "Verify dashboard/field/irrigation data while disconnected then restored.", "Running frontend/backend and browser network control.", "1. Load pages online. 2. Disconnect. 3. Navigate. 4. Restore.", "Do not claim offline data support unless retrieved data is actually cached/labelled/recovered.", data="<OFFLINE_BROWSER>", sit="X", remarks="Static inspection indicates static asset cache plus component localStorage paths; end-to-end not executed."),
tc("Internationalization", "Supported locales", "Verify configured dictionary coverage for all locales.", "Python pytest installed or static test execution environment.", "1. Run backend/tests/test_i18n_coverage.py. 2. Check locale sections.", "13 configured locales contain required dictionary sections.", data="en-IN, hi-IN, te-IN, kn-IN, ta-IN, mr-IN, bn-IN, ml-IN, gu-IN, pa-IN, or-IN, as-IN, ur-IN", status="BLOCKED", actual="Not Executed — pytest unavailable.", ready="BLOCKED", remarks="Existing test declares exactly these 13 locales."),
tc("Internationalization", "Full-page language switch", "Select Telugu and verify every localizable shell/page UI element switches.", "Running authenticated frontend.", "1. Select te-IN. 2. Inspect header/sidebar/nav/forms/modals/loading/error states across routes.", "All localizable UI is Telugu; no mixed English UI.", data="te-IN", status="PARTIALLY IMPLEMENTED", actual="Static audit found English strings in components/pages that do not use LanguageContext, including login, register, InstallPrompt, NetworkStatus and ai-recommendation.", defect="BUG001", remarks="See Current Status for affected paths."),
tc("Internationalization", "Persistence", "Change locale, navigate, refresh and re-login.", "Running frontend and authenticated user.", "1. Set locale. 2. Navigate/refresh. 3. Login again.", "localStorage persists locale; authenticated profile persistence restores it when API succeeds.", data="te-IN", sit="X", remarks="LanguageContext uses localStorage preferred_locale and PUT /users/profile."),
tc("Sarvam AI", "Translation and TTS", "Request translated text and recommendation audio with API failure cases.", "Sarvam credentials/network and owned recommendation.", "1. Call supported translation/TTS flow. 2. Simulate unsupported language/API error.", "Appropriate translated audio/text or controlled fallback/error.", data="<SARVAM_TEST_INPUT>", sit="X", remarks="backend/services/sarvam_ai.py and /recommendations/{id}/audio."),
tc("ML", "Prediction validation", "Call /api/ml/predict with valid, missing, wrong-type and boundary values.", "ML artifacts available.", "1. Submit each payload. 2. Verify response/error and model type.", "Valid input returns prediction; invalid schema returns HTTP 422.", data="<VALID_ML_FEATURES>", sit="X", remarks="Endpoint is not protected by get_current_user; assess intended public exposure."),
tc("ML", "Model loading and preprocessing", "Load production model/artifacts and compare inference features to training metadata.", "Python ML dependencies and artifacts.", "1. Run model load/prediction fixture. 2. Inspect feature order/scaler/encoder.", "Model/artifact load and preprocessing compatibility are demonstrated.", data="<ML_FEATURE_FIXTURE>", sit="X", remarks="ml/predict.py; model and preprocessing artifacts exist."),
tc("ML", "Model comparison/training", "Trigger authorized training and inspect training/comparison status.", "Admin account, dataset, ML runtime.", "1. POST /api/ml/train. 2. Poll status/results. 3. Set production model.", "Authorized process reports real metrics/status; production selection persists.", data="<ADMIN_ACCOUNT>", sit="X"),
tc("ML", "LSTM sequences", "Validate sufficient temporal sequence, insufficient history, shape and failure behavior.", "Dataset and TensorFlow runtime.", "1. Train/predict using valid and invalid sequences.", "Only supported LSTM workflow yields result; invalid sequence is handled.", data="<LSTM_SEQUENCE_FIXTURE>", sit="X", remarks="Training code implements LSTM; alert engine itself does not call LSTM."),
tc("Crop Disease Detection", "End-to-end workflow", "Verify image upload/camera/detection/advisory endpoint and UI.", "API/frontend implementation.", "1. Inspect registered routes and pages. 2. Execute if exposed.", "Image workflow is available and owned results are returned.", data="<TEST_IMAGE>", status="PARTIALLY IMPLEMENTED", actual="Database model CropDiseaseScan exists, but no corresponding FastAPI route or frontend page was found.", ready="NO"),
tc("Farmer Feedback", "Recommendation feedback", "Submit/list feedback tied to owned recommendation/field.", "API/frontend implementation.", "1. Inspect registered routes and pages. 2. Execute if exposed.", "Owned feedback is validated and persisted.", data="<TEST_RECOMMENDATION>", status="PARTIALLY IMPLEMENTED", actual="Database model FarmerAIFeedback exists, but no corresponding FastAPI route or frontend page was found.", ready="NO"),
tc("Reports", "CSV and PDF", "Generate a farmer CSV and PDF report.", "Farmer has farm/field; report dependencies.", "1. GET /farmer/reports?format=csv. 2. Repeat pdf. 3. Validate content/download.", "Correct owned farm/field data; valid downloadable files.", data="<VALID_FARMER_ACCOUNT>", sit="X", remarks="Implementation selects the first owned farm/field."),
tc("Security", "IDOR regression", "Attempt cross-tenant access on farms, fields, crops, sensors, recommendations, notifications, alerts and thresholds.", "Two farmer fixtures with separate data.", "1. Use Farmer B token for Farmer A IDs on every route. 2. Record each HTTP result.", "No Farmer A data is read, changed or deleted by Farmer B.", data="<CROSS_TENANT_IDS>", sit="X", remarks="Coverage must include every ID-bearing route, not only farms."),
tc("Security", "Admin ML authorization", "Attempt unauthenticated and FARMER calls to prediction/training/model-admin endpoints.", "API/database/ML runtime.", "1. Call /api/ml/predict without token. 2. Call training/status/set model as FARMER.", "Access matches intended authorization policy; unexpected public access is documented.", data="<VALID_FARMER_ACCOUNT>", sit="X", defect="BUG002", remarks="Static finding: /api/ml/predict declares no auth dependency; confirm intended policy at runtime."),
tc("Database", "Constraints and rollback", "Verify unique email, user role/status check constraints, FKs, threshold one-per-field, cascade behavior and rollback.", "Test PostgreSQL database and migration head.", "1. Apply migrations. 2. Attempt invalid/duplicate rows in transaction. 3. Verify rollback.", "Constraints reject invalid data and retain consistency.", data="<DATABASE_TEST_FIXTURE>", sit="X", remarks="Models and Alembic migrations inspected; no active database test run."),
tc("Frontend", "Route loading and responsive UI", "Load every discovered App Router page at supported breakpoints.", "Running frontend/backend and authenticated fixtures.", "1. Visit public/farmer/admin routes. 2. Test 320,360,375,390,414,768,1024,1280,1440 px. 3. Inspect overflow/focus/navigation.", "Pages respect authentication/authorization and remain usable without horizontal overflow.", data="<BROWSER_VIEWPORT_MATRIX>", sit="X", remarks="Routes discovered under frontend/app; visual/browser test not executed."),
tc("Accessibility", "Keyboard and semantics", "Test keyboard navigation, labels, ARIA, focus, contrast and touch targets.", "Running frontend and accessibility tooling/browser.", "1. Navigate all controls by keyboard. 2. Inspect screen-reader labels. 3. Audit contrast/touch targets.", "Controls have visible focus, accessible names and sufficient contrast/target size.", data="<ACCESSIBILITY_BROWSER>", remarks="Not evaluated by lint/typecheck alone."),
]

ISSUES = [
    ["Internationalization", "PARTIALLY IMPLEMENTED", "PARTIALLY IMPLEMENTED", "BUG001 — language provider exists, but several rendered UI files bypass it and retain English text after locale change.", "HIGH", "HIGH", "frontend/app/login/page.tsx; frontend/app/register/page.tsx; frontend/app/ai-recommendation/page.tsx; frontend/components/InstallPrompt.tsx; frontend/components/NetworkStatus.tsx", "Route all localizable UI through useTranslation; add dictionary keys and an end-to-end locale coverage test."],
    ["ML API Security", "PARTIALLY IMPLEMENTED", "NOT TESTED", "BUG002 — POST /api/ml/predict has no authentication dependency in its route signature; confirm whether public inference is intentional.", "HIGH", "HIGH", "backend/api/routes.py", "Require authentication/authorization if public inference is not an explicit product requirement; add negative authorization tests."],
    ["Farm Management", "PARTIALLY IMPLEMENTED", "NOT IMPLEMENTED", "No farm update route found.", "MEDIUM", "MEDIUM", "backend/api/routes.py", "Implement owned, validated update only if required."],
    ["Field Management", "PARTIALLY IMPLEMENTED", "NOT IMPLEMENTED", "No field update route found.", "MEDIUM", "MEDIUM", "backend/api/routes.py", "Implement owned, validated update only if required."],
    ["Authentication", "PARTIALLY IMPLEMENTED", "NOT IMPLEMENTED", "No backend logout/token revocation route found.", "LOW", "MEDIUM", "backend/api/routes.py; frontend/services/api.ts", "Document client-only logout or implement revocation if required."],
    ["Crop Disease Detection", "PARTIALLY IMPLEMENTED", "NOT IMPLEMENTED", "Persistence model exists but no endpoint/page exposes a disease scan workflow.", "MEDIUM", "MEDIUM", "database/models.py", "Implement API/UI and ownership validation if this is in scope."],
    ["Farmer Feedback", "PARTIALLY IMPLEMENTED", "NOT IMPLEMENTED", "Persistence model exists but no endpoint/page exposes feedback workflow.", "MEDIUM", "MEDIUM", "database/models.py", "Implement API/UI and recommendation ownership validation if this is in scope."],
    ["Test Automation", "PARTIALLY IMPLEMENTED", "BLOCKED", "Existing pytest tests cannot run in this environment because pytest is absent; tests also require configured PostgreSQL.", "MEDIUM", "HIGH", "backend/tests; requirements.txt", "Add pytest to development/test dependencies and run against isolated test DB in CI."],
]

def style_sheet(ws, widths):
    header_fill = PatternFill("solid", fgColor="1F4E78")
    thin = Side(style="thin", color="D9E2F3")
    for cell in ws[1]:
        cell.font = Font(color="FFFFFF", bold=True)
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = Border(bottom=thin)
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions
    for i, width in enumerate(widths, 1): ws.column_dimensions[get_column_letter(i)].width = width
    for row in ws.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = Alignment(vertical="top", wrap_text=True)
            cell.border = Border(bottom=thin)

def main():
    wb = Workbook()
    ws = wb.active; ws.title = "Test Cases"; ws.append(HEADERS)
    for i, row in enumerate(CASES, 1): ws.append([f"TC{i:03d}"] + row)
    style_sheet(ws, [13,18,20,42,34,15,12,10,14,48,42,48,24,12,26,13,48])
    for r in range(2, ws.max_row + 1): ws.row_dimensions[r].height = 70
    status_dv = DataValidation(type="list", formula1='"PASS,FAIL,BLOCKED,NOT TESTED,NOT IMPLEMENTED,PARTIALLY IMPLEMENTED"'); ws.add_data_validation(status_dv); status_dv.add(f"M2:M{ws.max_row}")
    priority_dv = DataValidation(type="list", formula1='"CRITICAL,HIGH,MEDIUM,LOW"'); ws.add_data_validation(priority_dv); priority_dv.add(f"N2:N{ws.max_row}")
    ready_dv = DataValidation(type="list", formula1='"YES,NO,BLOCKED"'); ws.add_data_validation(ready_dv); ready_dv.add(f"F2:F{ws.max_row}")
    colors = {"PASS":"C6EFCE", "FAIL":"FFC7CE", "BLOCKED":"FFEB9C", "NOT TESTED":"D9EAF7", "NOT IMPLEMENTED":"D9D9D9", "PARTIALLY IMPLEMENTED":"FCE4D6"}
    for value, color in colors.items(): ws.conditional_formatting.add(f"M2:M{ws.max_row}", CellIsRule(operator="equal", formula=[f'"{value}"'], fill=PatternFill("solid", fgColor=color)))

    summary = wb.create_sheet("Test Summary"); summary.append(["Metric", "Value"])
    metrics = [("Total Test Cases", f"=COUNTA('Test Cases'!A2:A{ws.max_row})"), ("PASS", "=COUNTIF('Test Cases'!M:M,\"PASS\")"), ("FAIL", "=COUNTIF('Test Cases'!M:M,\"FAIL\")"), ("BLOCKED", "=COUNTIF('Test Cases'!M:M,\"BLOCKED\")"), ("NOT TESTED", "=COUNTIF('Test Cases'!M:M,\"NOT TESTED\")"), ("NOT IMPLEMENTED", "=COUNTIF('Test Cases'!M:M,\"NOT IMPLEMENTED\")"), ("PARTIALLY IMPLEMENTED", "=COUNTIF('Test Cases'!M:M,\"PARTIALLY IMPLEMENTED\")"), ("Functional Tests", "=COUNTIF('Test Cases'!G:G,\"X\")"), ("SIT Tests", "=COUNTIF('Test Cases'!H:H,\"X\")"), ("Performance Tests", "=COUNTIF('Test Cases'!I:I,\"X\")"), ("Pass %", "=IFERROR(B3/B2,0)"), ("Fail %", "=IFERROR(B4/B2,0)"), ("Execution %", "=IFERROR((B3+B4)/B2,0)")]
    for row in metrics: summary.append(row)
    style_sheet(summary, [28,24]); [setattr(summary[f"B{r}"], "number_format", "0.00%") for r in (12,13,14)]

    coverage = wb.create_sheet("Module Coverage"); coverage.append(["Module", "Total Test Cases", "Implemented", "Tested", "Passed", "Failed", "Blocked", "Not Implemented", "Coverage %"])
    modules = sorted({r[0] for r in CASES})
    for idx, module in enumerate(modules, 2):
        coverage.append([module, f'=COUNTIF(\'Test Cases\'!B:B,A{idx})', f'=B{idx}-COUNTIFS(\'Test Cases\'!B:B,A{idx},\'Test Cases\'!M:M,"NOT IMPLEMENTED")', f'=COUNTIFS(\'Test Cases\'!B:B,A{idx},\'Test Cases\'!M:M,"PASS")+COUNTIFS(\'Test Cases\'!B:B,A{idx},\'Test Cases\'!M:M,"FAIL")+COUNTIFS(\'Test Cases\'!B:B,A{idx},\'Test Cases\'!M:M,"BLOCKED")', f'=COUNTIFS(\'Test Cases\'!B:B,A{idx},\'Test Cases\'!M:M,"PASS")', f'=COUNTIFS(\'Test Cases\'!B:B,A{idx},\'Test Cases\'!M:M,"FAIL")', f'=COUNTIFS(\'Test Cases\'!B:B,A{idx},\'Test Cases\'!M:M,"BLOCKED")', f'=COUNTIFS(\'Test Cases\'!B:B,A{idx},\'Test Cases\'!M:M,"NOT IMPLEMENTED")', f'=IFERROR(D{idx}/B{idx},0)'])
    style_sheet(coverage, [28,18,16,14,14,14,14,20,16])
    for cell in coverage["I"][1:]: cell.number_format = "0.00%"

    how = wb.create_sheet("How To Use"); how.append(["Column", "Usage"])
    uses = [("Test Case ID", "Unique, stable identifier."), ("Module / Sub Module", "Repository-derived functional area."), ("Test Case Description", "What the test verifies."), ("Preconditions / Dependencies", "Environment, account, data, and service requirements."), ("TC Ready for Testing", "YES = runnable; NO = not implemented; BLOCKED = dependency unavailable."), ("Functional / SIT / Performance", "X identifies behavior, integration, or an actual performance scenario."), ("Test Steps", "Execute in order and preserve evidence."), ("Expected Result", "Observable product behavior or status code based on the implementation."), ("Actual Result", "Observed output; Not Executed means no runtime claim."), ("Status", "Only PASS, FAIL, BLOCKED, NOT TESTED, NOT IMPLEMENTED, PARTIALLY IMPLEMENTED."), ("Priority", "CRITICAL/HIGH/MEDIUM/LOW risk priority."), ("Test Data", "Use placeholders only; never record secrets."), ("Defect ID", "BUG reference for identified issues."), ("Remarks", "Actual route/file traceability and constraints.")]
    for row in uses: how.append(row)
    style_sheet(how, [32,110])

    current = wb.create_sheet("Current Status"); current.append(["Module", "Implementation Status", "Testing Status", "Known Issue", "Severity", "Priority", "Affected File", "Recommendation"])
    for row in ISSUES: current.append(row)
    style_sheet(current, [24,24,20,58,12,12,58,65])
    for r in range(2, current.max_row + 1): current.row_dimensions[r].height = 65

    wb.save(OUT)
    # Re-open ensures the produced OOXML archive is readable and all mandatory sheets exist.
    check = load_workbook(OUT, data_only=False)
    assert check.sheetnames == ["Test Cases", "Test Summary", "Module Coverage", "How To Use", "Current Status"]
    assert len({c.value for c in check["Test Cases"]["A"][1:]}) == len(CASES)
    assert not any("PASSWORD@" in str(cell.value).upper() for sh in check for row in sh.iter_rows() for cell in row)
    print(f"Created {OUT} with {len(CASES)} test cases.")

if __name__ == "__main__": main()
